### ISSUE TITLE
Bump to mongodb 3.6.3

### ISSUE THREAD

**Issue by dawnerd** [Marsup/hapi-mongodb#45]
We're in the process of moving our node up to v14 and noticed a notices:

```
circles-api_1      | (node:193) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
circles-api_1      |     at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
circles-api_1      |     at Object.get (internal/modules/cjs/loader.js:664:5)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/db_ops.js:16:42)
circles-api_1      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
circles-api_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
circles-api_1      |     at Module.load (internal/modules/cjs/loader.js:928:32)
circles-api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
circles-api_1      |     at Module.require (internal/modules/cjs/loader.js:952:19)
circles-api_1      |     at require (internal/modules/cjs/helpers.js:88:18)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/collection_ops.js:5:23)
circles-api_1      | (node:193) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
circles-api_1      |     at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
circles-api_1      |     at Object.get (internal/modules/cjs/loader.js:664:5)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/db_ops.js:17:44)
circles-api_1      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
circles-api_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
circles-api_1      |     at Module.load (internal/modules/cjs/loader.js:928:32)
circles-api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
circles-api_1      |     at Module.require (internal/modules/cjs/loader.js:952:19)
circles-api_1      |     at require (internal/modules/cjs/helpers.js:88:18)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/collection_ops.js:5:23)
circles-api_1      | (node:193) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
circles-api_1      |     at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
circles-api_1      |     at Object.get (internal/modules/cjs/loader.js:664:5)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/db_ops.js:18:43)
circles-api_1      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
circles-api_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
circles-api_1      |     at Module.load (internal/modules/cjs/loader.js:928:32)
circles-api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
circles-api_1      |     at Module.require (internal/modules/cjs/loader.js:952:19)
circles-api_1      |     at require (internal/modules/cjs/helpers.js:88:18)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/collection_ops.js:5:23)
circles-api_1      | (node:193) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
circles-api_1      |     at emitCircularRequireWarning (internal/modules/cjs/loader.js:650:11)
circles-api_1      |     at Object.get (internal/modules/cjs/loader.js:664:5)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/db_ops.js:19:46)
circles-api_1      |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
circles-api_1      |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
circles-api_1      |     at Module.load (internal/modules/cjs/loader.js:928:32)
circles-api_1      |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
circles-api_1      |     at Module.require (internal/modules/cjs/loader.js:952:19)
circles-api_1      |     at require (internal/modules/cjs/helpers.js:88:18)
circles-api_1      |     at Object.<anonymous> (/home/app/src/node_modules/mongodb/lib/operations/collection_ops.js:5:23)
circles-api_1      | [hapi-mongodb,info] MongoClient connection created for {"url":"mongodb://mongo:27017/circlesv3","decorate":true,"settings":{"useNewUrlParser":true,"useUnifiedTopology":true}}
```

Seems bumping this helped: https://github.com/firstandthird/hapi-mongodb/pull/2/commits/7f05dd15d1509abc32c42a65ef95e2649ab69c09#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R23

I made some other changes there before realizing we had forked this. If you want I can get a pr to bump just mongodb.

**Comment by Marsup** [comment]
The semver already allows for this version to be installed, you likely have another problem going on.
